version: '3.6'

services:
    nginx:
        container_name: appto-users-nginx
        image: nginx:1.15-alpine
        restart: unless-stopped
        ports:
            - "8030:80"
        volumes:
            - .:/app:delegated
            - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        container_name: appto-users-php
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/app:delegated
        env_file:
            - .env
