services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #SERVICES
    #BookingRequest Checkers
    Appto\Booking\Domain\Request\BookingPriceCalculator: ~

    Appto\Booking\Domain\Request\AvailabilityBookingRequestChecker: ~
    Appto\Booking\Domain\Request\CapacityBookingRequestChecker: ~

    Appto\Booking\Domain\Request\BookingRequestChecker: '@Appto\Booking\Domain\Request\BookingRequestCheckerComposite'
    Appto\Booking\Domain\Request\PriceCalculator: '@Appto\Booking\Domain\Request\BookingPriceCalculator'

    Appto\Booking\Domain\Request\BookingRequestCheckerComposite:
        calls:
         -  method: setCheckers
            arguments:
                - { param1: '@Appto\Booking\Domain\Request\AvailabilityBookingRequestChecker', aram2: '@Appto\Booking\Domain\Request\CapacityBookingRequestChecker' }





